apiVersion: v1
kind: Pod
metadata:
   name: webapp-queue
   labels:
       name: fleetman-queue
       app: webapp
spec:
   containers:
      - name: webapp-queue
        image: richardchesterwood/k8s-fleetman-queue:release1

