kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name:  new-joiner
   namespace: default
rules:
- apiGroups: [""]    # "" indicates the core API group   (v1)    deployment is in beta/v1
  resources: ["*"]     # pods , services not deployment
  verbs: ["get", "watch", "list"]
		
     
