kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name:  new-joiner
   namespace: default
rules:
- apiGroups: ["","apps"]    # "" indicates the core API group and apps  (v1)    deployment is in apps/v1
  resources: ["*"]     # pods , services and  deployment
  verbs: ["get", "watch", "list"]
		
     
